# Generated by Django 4.2.9 on 2024-02-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramo', models.PositiveIntegerField(default=0)),
                ('cupos_disponibles', models.PositiveIntegerField(default=0)),
                ('fecha_clase', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='clases')),
            ],
        ),
        migrations.CreateModel(
            name='TipoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada'), ('Realizada', 'Realizada')], default='Pendiente', max_length=10)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.clase')),
            ],
        ),
    ]
