# Generated by Django 4.2.9 on 2024-02-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='clase',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.instructor'),
        ),
        migrations.AddField(
            model_name='clase',
            name='tipo_clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.tipoclase'),
        ),
        migrations.AddField(
            model_name='clase',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to='usuarios.cliente'),
        ),
    ]
