# Generated by Django 4.2.9 on 2024-02-15 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
        ('clases', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='tramo',
            field=models.PositiveIntegerField(choices=[(20, 20), (40, 40), (60, 60), (80, 80), (100, 100), (120, 120)], default=20),
        ),
        migrations.AlterField(
            model_name='clase',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='usuarios.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
