# Generated by Django 4.2.9 on 2024-02-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_alter_clase_instructor_alter_clase_tramo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='valido',
            field=models.BooleanField(default=True),
        ),
    ]
