# Generated by Django 4.2.9 on 2024-02-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_clase_valido'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nombre_clase',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
