# Generated by Django 4.2.9 on 2024-02-15 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_reserva_nombre_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.clase'),
        ),
    ]
