# Generated by Django 4.2.9 on 2024-02-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_alter_clase_instructor_alter_clase_tramo_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_membresia',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Suspendida', 'Suspendida')], default='Activa', max_length=10),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
