# Generated by Django 4.2.9 on 2024-02-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_alter_clase_instructor_alter_clase_tramo_and_more'),
        ('usuarios', '0002_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clases_asignadas',
            field=models.ManyToManyField(blank=True, related_name='clases_asignadas', to='clases.clase'),
        ),
    ]
